@OrderProcessing.Api_HostAddress = http://localhost:5078

POST {{OrderProcessing.Api_HostAddress}}/api/orders/process
Content-Type: application/json

{ "orderId": "order-123" }

###

GET {{OrderProcessing.Api_HostAddress}}/api/orders/stats
Accept: application/json

###

GET {{OrderProcessing.Api_HostAddress}}/health
Accept: application/json

###
